game_data_set = {
    "bomb-game": {
        "game_id": "bomb-game",
        "description": "주어진 시간동안 핸드폰을 옆 사람에게 넘겨주세요! 타이머가 끝날때 핸드폰을 갖고 있는 사람이 벌칙 당첨!",
        "name": "폭탄 돌리기 게임",
        "main_image_url": "images/game/bomb-game/main-image.png",
        "recommended_people_range": [1, 50],
        "html_link": "bombGame.html",
    },
    "hunch-game": {
        "game_id": "hunch-game",
        "recommended_people_range": [3, 50],
        "description": "지금부터 서로의 눈치를 보면서 순서대로 숫자를 외쳐주세요! 가장 늦게 외치거나, 동시에 외친 사람이 벌칙 당첨!",
        "name": "눈치게임",
        "main_image_url": "images/game/hunch-game/main-image.png",
        "html_link": "hunchGame.html",
    },
    "initial-consonant-quiz": {
        "game_id": "initial-consonant-quiz",
        "recommended_people_range": [1, 50],
        "description": "화면에 제시된 초성을 이용하여 단어를 조합하세요! 가장 늦게 조합한 사람이 벌칙 당첨 !",
        "name": "초성퀴즈",
        "main_image_url": "images/game/initial-consonant-quiz/main-image.png",
        "html_link": "initialConsonantQuiz.html",
    },
    "korean-game": {
        "game_id": "korean-game",
        "recommended_people_range": [1, 50],
        "description": "주어진 시간동안 자유롭게 이야기하세요! 영어나 외래어를 말한 사람이 벌칙 당첨!",
        "name": "훈민정음 게임",
        "main_image_url": "images/game/korean-game/main-image.png",
        "html_link": "koreanGame.html",
    },
    "finger-game": {
        "game_id": "finger-game",
        "recommended_people_range": [1, 50],
        "description": "지금부터 손바닥을 펼쳐주세요! 5개의 목숨이 있고, 한명씩 돌아가면서 서로의 목숨을 깎아주세요! 손가락이 다 접힌 사람이 벌칙 당첨!",
        "name": "손병호 게임",
        "main_image_url": "images/game/finger-game/main-image.png",
        "html_link": "fingerGame.html",
    },
    "train-game": {
        "game_id": "train-game",
        "recommended_people_range": [5, 50],
        "description": "화면에 제시된 지하철 호선에 따라 지하철 역 이름을 돌아가면서 말해주세요! 틀린 사람이 벌칙 당첨!",
        "name": "지하철 호선 게임",
        "main_image_url": "images/game/train-game/main-image.png",
        "html_link": "trainGame.html",
    },
    "baskin-robbins": {
        "game_id": "baskin-robbins",
        "recommended_people_range": [1, 50],
        "description": "한사람당 최대 연속 세가지 숫자를 외칠 수 있고, 최종적으로 31을 외치는 사람이 벌칙 당첨!",
        "name": "베스킨라빈스 31",
        "main_image_url": "images/game/baskin-robbins/main-image.png",
        "html_link": "baskinRobbins.html",
    },
    "image-game": {
        "game_id": "image-game",
        "recommended_people_range": [3, 50],
        "description": "화면에 주어진 이미지와 가장 비슷한 사람을 지목해주세요! 지목 당한 사람이 벌칙 당첨!",
        "name": "이미지 게임",
        "main_image_url": "images/game/image-game/main-image.png",
        "html_link": "imageGame.html",
    },
    "balance-game": {
        "game_id": "balance-game",
        "recommended_people_range": [3, 50],
        "description": "주어진 시간동안 토론을 하고 두가지 상황 중 한가지를 선택해주세요. 더 적은 쪽에 거수한 사람들이 벌칙 당첨 !",
        "name": "밸런스 게임",
        "main_image_url": "images/game/balance-game/main-image.png",
        "html_link": "balanceGame.html",
    },
    "iam-ground": {
        "game_id": "iam-ground",
        "recommended_people_range": [1, 50],
        "description": "주어진 주제에 맞게 자기소개를 하고, 박자에 맞춰서 서로에게 공격해주세요! 틀린 사람이 벌칙 당첨!",
        "name": "아이엠그라운드 게임",
        "main_image_url": "images/game/iam-ground/main-image.png",
        "html_link": "iamGround.html",
    },
}
